name: AlreadyPossible

options:
    bundleIdPrefix: com.AlreadyPossible
    minimumXcodeGenVersion: 2.35.0
    xcodeVersion: 14.1
    deploymentTarget:
        iOS: 16.0
    groupSortPosition: top
    
configs:
    Debug: debug
    Beta: release
    AppStore: release
    
targets:
    AlreadyPossible:
        type: application
        platform: iOS
        deploymentTarget: 16.0
        settings:
            base:
                MARKETING_VERSION: 1.0
        sources:
            - path: AlreadyPossible
